services:
  airflow:
    build:
      context: airflow
      dockerfile: Dockerfile
    environment:
      - AIRFLOW__CORE__ENABLE_XCOM_PICKLING=True
    volumes:
      - ./src/pipeline:/opt/airflow
      - ./src/pipeline/dags:/opt/airflow/dags
      - ./src/pipeline/plugins:/opt/airflow/plugins
      - ./src/pipeline/data:/opt/airflow/data
    ports:
      - "8080:8080"
    command: airflow standalone
    networks:
      - mlops-net
  minio:
    image: minio/minio
    container_name: minio
    command: "server /data --console-address ':9001'"
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
    ports:
      - 9000:9000
      - 9001:9001
    networks:
      - mlops-net
    volumes:
      - ./minio/data:/data
  api:
    build:
      context: api
      dockerfile: src/api/Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - minio
      - airflow

networks:
  mlops-net:
    driver: bridge
