channels:
- conda-forge
dependencies:
- python=3.9.18
- pip<=24.0
- pip:
  - mlflow==2.3
  - catboost==1.2
  - cloudpickle==2.2.1
  - numpy==1.26.4
  - pandas==2.0.1
  - scikit-learn==1.2.2
  - scipy==1.13.1
name: mlflow-env
